### ISSUE TITLE
Documentation discrepancy

### ISSUE THREAD

**Issue by matejak** [exo-addons/onlyoffice#11]
There is this section in the README:
```
...
When you have installed Docker, you need a single command to start the Document Server on-premise:

sudo docker run -i -t -d -p 80:80 onlyoffice/documentserver

The Document Server needs only port 80 by default, but you also can run in on HTTPS. Follow its guides for more detailed setup.

To check you have running Document Server successfuly, open a page on its address http://DOCUMENT_SERVER_HOST/OnlineEditorsExample/
...
```
When running the documentserver as described using the Docker command, accessing `http://DOCUMENT_SERVER_HOST/OnlineEditorsExample/` yields an error - the result reads `Cannot GET /OnlineEditorsExample/`. Accessing `http://DOCUMENT_SERVER_HOST/` displays a "Thank you for choosing ONLYOFFICE!, Document Server is running" message, so the document server itself is OK.
I have checked all available Onlyoffice images, and for example tags `4.4.3.7` and `5.0.5.26` behave all the same (I have tried even more tags, but I don't recall which ones). When trying to find any documentation on what `OnlineEditorsExample` is supposed to show, I found none.
What does this mean? Is it just a documentation error, or has the document server changed its API?

**Comment by pnedonosko** [comment]
Hi Matej, yes it looks that Onlyoffice disto changed the path to the example app. But it is not used by the add-on at all, if you see the document server is up and running it's enough.

**Comment by matejak** [comment]
Great, thank you for your explanation, I have set up a PR to help to clarify the documentation, hope you like it!
