### ISSUE TITLE
Use Document Server token to secure access

### ISSUE THREAD

**Issue by pnedonosko** [exo-addons/onlyoffice#14]
Document Server can use [JSON tokens](https://api.onlyoffice.com/editors/security) to secure access to its services. Check if these tokens also can be used to ensure access to the add-on REST services by the document server.

**Comment by pnedonosko** [comment]
This issue originally suggested in #3.

**Comment by pnedonosko** [comment]
Planned for 1.2.x version (for Platform 5.0.x).

**Comment by pnedonosko** [comment]
Moved to 1.4.x version (Platform 5.2.x scope)

**Comment by VladMartyshevskyi** [comment]
Resolved
