### ISSUE TITLE
Document URLs may contain port -1 but should be without an one

### ISSUE THREAD

**Issue by pnedonosko** [exo-addons/onlyoffice#16]
One of customers reported that when running in their infra, document URLs generated by the add-on contain port -1, but it should be an URL without port set.

**Comment by pnedonosko** [comment]
How problem looks on user side with -1 ports:
![capture du 2018-02-14 11-05-29_censored](https://user-images.githubusercontent.com/1451697/36207013-20ec9f38-119d-11e8-8f0b-d2eb9d425b85.png)

**Comment by madhifallah** [comment]
fixed thanks
