### ISSUE TITLE
"loading" css class conflicts with share document popup style

### ISSUE THREAD

**Issue by madhifallah** [exo-addons/onlyoffice#17]
onlyoffice.css:24

.loading {
    width: 100%;
    height: 100%;
    position: relative;
    border: 0px;
    min-width: 665px;
    min-height: 550px;
    margin-bottom: 15px;
}

this conflicts with share document popup and make it very large.

![capture du 2018-02-14 15-42-05](https://user-images.githubusercontent.com/2385389/36210568-072c6f72-119f-11e8-97e8-ca258caf5544.png)

**Comment by pnedonosko** [comment]
@madhifallah does his commit fix the problem?
