### ISSUE TITLE
Platform Version 5.0.0 - NOT Supported

### ISSUE THREAD

**Issue by kmanojkumar** [exo-addons/onlyoffice#21]
Hey, Thanks for creating this useful Addon. I am trying to install it in **eXoPlatform Version 5.0.0** (Latest Community Edition) - It says the **ADDON IS NOT COMPATIBLE?**

Can you fix that please?

**Comment by plamarque** [comment]
Did you try to force with the no-compat option (I don't know if it will work, just pointing to this option in case it would magically work with 5.0).

**Comment by pnedonosko** [comment]
Hi, thank you for warm words K Manoj Kumar. Try install latest unstable version 1.2.0-RC1 use:
```
 ./addon.sh install --unstable exo-onlyoffice
```
This version is the same as v1.1.2 for Platform 4.4.

**Comment by ganababuapp** [comment]
It works @pnedonosko and @plamarque! Thank you.

**Comment by kmanojkumar** [comment]
That worked! Thanks, @pnedonosko and @plamarque!
