### ISSUE TITLE
Edit Online on activity stream

### ISSUE THREAD

**Issue by plamarque** [exo-addons/onlyoffice#30]
Just like "Open in Word", it would be very convenient to have an "Edit Online" action on each document activity in the stream.
<img width="231" alt="edit-online-activity-stream" src="https://user-images.githubusercontent.com/1451697/52269104-eac87a00-2945-11e9-9932-1a05679c0842.png">

**Comment by pnedonosko** [comment]
Fixed in 1.4.0-M08
