### ISSUE TITLE
Edit Online on Document preview

### ISSUE THREAD

**Issue by plamarque** [exo-addons/onlyoffice#31]
Just like "Open in Word" buttons, it would be very convenient to have "Edit Online" buttons on Document Preview interface.
<img width="832" alt="edit-online-docpreview" src="https://user-images.githubusercontent.com/1451697/52269152-0469c180-2946-11e9-8d7e-f5fb3eff5dbb.png">

**Comment by pnedonosko** [comment]
Fixed in 1.4.0-M09
