### ISSUE TITLE
Can't edit a shared document

### ISSUE THREAD

**Issue by plamarque** [exo-addons/onlyoffice#32]
With user A, go on a .docx in Documents app.
Click Share and share to user B with edit permission
With user B, check a notification has been received, click on it : user B is directed to /Documents/Shared/test.docx in "Personal Documents"
Edit Online button does not appear 

In fact, Share function generates a test.docx symlink to the original document in order to give access to the document without giving access to the space.  I guess the Connector is not able to recognize symlinks yet.

**Comment by VladMartyshevskyi** [comment]
Seems to be fixed in the previous releases.
