### ISSUE TITLE
AccessDeniedException prevents creation of editor for shared documents

### ISSUE THREAD

**Issue by pnedonosko** [exo-addons/onlyoffice#7]
When one user shares his personal document or a document from space where another is not a member, this another user cannot open the document for editing in Onlyoffice add-on. This happens due to insufficient permissions of the document parent (and it's OK). But the add-on needs read a parent folder name to fill Onlyoffice configuration JSON's "folder" field for an editor JS SDK. This field will be used for "Location" text in Onlyoffice's editor Document->Info form.

This can be fixed by discovering a shared file path, if exception happen, and guessing a name for that "Location": like "John Smith's personal document" or "Product Space document".

**Comment by VladMartyshevskyi** [comment]
Fixed
